# Site settings
title: Ian Rice Tattoos
email: bentlifetattoo@gmail.com
url: https://ianricetattoos.com
description: "Ian Rice Tattoos"
keywords: "tattoo"
skills: "Artist"
meta_author: Rice Ian

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: eed3dc
  primary-rgb: "83,136,124"
  secondary: 73b0a2
  secondary-dark: 53887c

# Footer settings
footer:
  copyright: Ian Rice
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/ianricetattoos

# Postal address (add as many lines as necessary)
address:
#  - line: Phoenix Tattoo Company
#  - line: 1760 S Broadway Blvd
  - line: Denver, CO 80210

# Credits content
credits: '<a href="https://jeromelachaud.com/freelancer-theme">freelancer</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
